apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bmove7w6y-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bmove7w6y-go 
  name: bmove7w6y-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: bmove7w6y-go 
